import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn("relative bg-black text-gray-200", urbanist.className)}
      >
        {children}
        {/* <div className="background-gradient absolute inset-0 -z-50 max-h-screen" /> */}
        <div className="pointer-events-none absolute inset-0 -z-50 h-full bg-[url('/noisetexture.jpg')] mix-blend-hard-light opacity-[0.07]" />
      </body>
    </html>
  );
}
